services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: course_assistant
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres

  streamlit:
    build:
      context: ../..
      dockerfile: 05-monitoring/monitoring-lab/Dockerfile
    env_file:
      - ../../.env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=course_assistant
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:
